<?php

/**
 * PluginiframeSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginiframeSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginiframeSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginiframeSlot');
    }
}